export const AUDIT_EVENTS = {
  JOIN: "JOIN",
  LEAVE: "LEAVE",
  LOCAL_JOIN: "LOCAL_JOIN",
  LOCAL_LEAVE: "LOCAL_LEAVE",
  MIC_ON: "MIC_ON",
  MIC_OFF: "MIC_OFF",
  CAMERA_ON: "CAMERA_ON",
  CAMERA_OFF: "CAMERA_OFF",
  SCREEN_SHARE_START: "SCREEN_SHARE_START",
  SCREEN_SHARE_STOP: "SCREEN_SHARE_STOP",
} as const;
