import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ToastProvider from "./toast-provider";
import Header from "@/components/homepage/header/header";
import { AuthProvider } from "@/contexts/AuthContext";
import { getLocaleFromCookie } from "@/utils/getLocale";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocaleFromCookie();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>

          {/* Adding this for blur effect while triggering payment */}
          <div id="main-app-layout" className="transition-all duration-500">
            <Header />
            {children}
          </div>
          {/* render page.tsx here */}
          <Script
            src="https://www.payhere.lk/lib/payhere.js"
            strategy="lazyOnload"
          />
          <ToastProvider />
        </AuthProvider>
      </body>
    </html>
  );
}